INSERT INTO public.funnel_stages (name, sort_order, color, is_final) VALUES
('Novo Lead', 1, '#3498db', false),
('Qualificado', 2, '#9b59b6', false),
('Visita Agendada', 3, '#f1c40f', false),
('Em Negociação', 4, '#e67e22', false),
('Proposta Enviada', 5, '#e74c3c', false),
('Venda Realizada', 6, '#2ecc71', true),
('Perdido', 7, '#95a5a6', true);

INSERT INTO public.settings_lookup (category, label, value, sort_order) VALUES
('origem', 'Inbound', 'inbound', 1),
('origem', 'Outbound', 'outbound', 2),
('status', 'Novo', 'novo', 1),
('status', 'Em Atendimento', 'em_atendimento', 2),
('status', 'Qualificado', 'qualificado', 3),
('status', 'Em Negociação', 'em_negociacao', 4),
('status', 'Venda Realizada', 'venda_realizada', 5),
('status', 'Perdido', 'perdido', 6),
('prioridade', 'Baixa', 'baixa', 1),
('prioridade', 'Média', 'media', 2),
('prioridade', 'Alta', 'alta', 3),
('prioridade', 'Urgente', 'urgente', 4),
('tipo_imovel', 'Apartamento', 'apartamento', 1),
('tipo_imovel', 'Casa', 'casa', 2),
('tipo_imovel', 'Terreno', 'terreno', 3),
('tipo_imovel', 'Lote', 'lote', 4),
('tipo_imovel', 'Sala Comercial', 'sala_comercial', 5),
('tipo_imovel', 'Cobertura', 'cobertura', 6),
('tipo_imovel', 'Flat', 'flat', 7),
('perfil', 'Morador', 'morador', 1),
('perfil', 'Investidor', 'investidor', 2),
('tipo_atividade', 'Ligação', 'ligacao', 1),
('tipo_atividade', 'Mensagem', 'mensagem', 2),
('tipo_atividade', 'Reunião', 'reuniao', 3),
('tipo_atividade', 'Visita', 'visita', 4),
('tipo_atividade', 'Observação', 'observacao', 5),
('motivo_perda', 'Preço', 'preco', 1),
('motivo_perda', 'Localização', 'localizacao', 2),
('motivo_perda', 'Comprou com outro', 'comprou_com_outro', 3),
('motivo_perda', 'Desistiu', 'desistiu', 4),
('motivo_perda', 'Sem retorno', 'sem_retorno', 5),
('motivo_perda', 'Financiamento negado', 'financiamento_negado', 6),
('motivo_perda', 'Outro', 'outro', 7);
